name: simpyinvoice_dev

on: 
  push:
    branches: 
      - develop

jobs:
  test:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Check Python Version
      run: |
        python --version
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
    - name: Install dependencies
      run: |
        pipenv install
    - name: Run Tests
      run: |
        pytest
