name: simpyinvoice_dev

on: push

env:
  FLASK_APP: simpyinvoice.py
  APP_NAME: simpyinvoice
  FLASK_CONFIG: test
  FLASK_ENV: testing
  SIMPYINVOICE_SECRET_KEY: ${{ secrets.SIMPYINVOICE_SECRET_KEY }}

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Check Python Version
      run: |
        python --version

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/dev.txt
    - name: Deploy Database Changes
      run: |
        flask db upgrade
    - name: Unit Tests
      run: |
        pytest -vv -k "unit_tests"
    - name: Integration Tests
      run: |
        pytest -vv -k "integration_tests"
    - name: Functional Tests
      run: |
        pytest -vv -k "functional_tests"
